
- 이전 Chapter에서는 Server Action을 사용하여 데이터를 변경하는 방법에 대해 알아보았다.
	- 이번에는 JavaScript의 try/catch 문과 Next.js API를 사용하여 오류를 어떻게 처리할 수 있는지 알아볼 것이다.

- 이번 Chapter에서는 다음 주제를 다룬다
	1. `error.tsx` 파일을 사용하여 라우트 세그먼트에서 발생한 오류를 잡고, 사용자에게 대체 UI를 표시하는 방법.
	2. `notFound` 함수와 `not-found` 파일을 사용하여 존재하지 않는 리소스에 대한 404 오류를 처리하는 방법.
	3. 서버 액션에 `try/catch` 문을 추가하여 오류를 처리하는 방법.


#### 1. Adding `try/catch` to Server Actions (서버 액션에 `try`/`catch`구문 추가)

- 먼저, JavaScript의 `try/catch` 문을 서버 액션에 추가하여 오류를 처리해 보자.
	- 아래 코드를 참고하자.

> `/app/lib/actions.ts`
```ts

// ...

// 송장 데이터 생성부분 수정
export async function createInvoice(formData: FormData) {
  const { customerId, amount, status } = CreateInvoice.parse({
    customerId: formData.get("customerId"),
    amount: formData.get("amount"),
    status: formData.get("status"),
  });

  const amountInCents = amount * 100;
  const date = new Date().toISOString().split("T")[0];

  try { // 수정
    await sql`
    INSERT INTO invoices (customer_id, amount, status, date)
    VALUES (${customerId}, ${amountInCents}, ${status}, ${date})
  `;
  } catch (e) {
    return {
      message: "DB Error : Faileed to Create Invoice",
    };
  }

  revalidatePath("/dashboard/invoices");
  redirect("/dashboard/invoices"); // add code
}

// 송장 데이터 업데이트부분 수정
export async function updateInvoice(id: string, formData: FormData) {
  const { customerId, amount, status } = UpdateInvoice.parse({
    customerId: formData.get("customerId"),
    amount: formData.get("amount"),
    status: formData.get("status"),
  });

  const amountInCents = amount * 100;

  try {
    await sql`
    UPDATE invoices
    SET customer_id = ${customerId}, amount = ${amountInCents}, status = ${status}
    WHERE id = ${id}
  `;
  } catch (e) {
    return {
      message: "DB Error : Faileed to Update Invoice",
    };
  }

  // 클라이언트 캐시 무효화 및 서버 요청 갱신
  revalidatePath("/dashboard/invoices");
  // 업데이트 후 인보이스 페이지로 리다이렉트
  redirect("/dashboard/invoices");
}

// 송장 데이터 삭제부분 수정
export async function deleteInvoice(id: string) {
  try {
    await sql`DELETE FROM invoices WHERE id = ${id}`;
    revalidatePath("/dashboard/invoices");
    return { message: "Deleted Invoice." };
  } catch (error) {
    return { message: "Database Error: Failed to Delete Invoice." };
  }
}
```

- 위 코드를 보면 `redirect`가 `try/catch` 구문 밖에서 호출되는 것에 주목할 필요가 있다.
	- Next.js에서 `redirect` 함수는 내부적으로 **오류를 던져서** `redirect`를 실행한다. 따라서 `redirect`가 `try/catch` 블록 안에 있을 경우, `redirect`가 호출되면 오류가 발생하여 바로 `catch` 블록에서 잡히게 된다.
	
	- 그래서, `redirect` 함수를 사용할 때는 `try` 영역 내 코드흐름이 성공한 다음에 도달할 수 있게끔 구현할 필요가 있다.  


- 이제 Server Action에서 오류가 발생했을 때 어떻게 되는지 확인해 보자. 
	- 이를 위해, 예시로 `deleteInvoice` 액션에서 함수 상단에 오류를 발생시키는 코드를 추가하여 의도적인 오류를 발생시켜보자.
```ts
export async function deleteInvoice(id: string) {
  // 의도적 에러 발생
  throw new Error("Failed to Delete Invoice");

  // 도달불가
  try {
    await sql`DELETE FROM invoices WHERE id = ${id}`;
    revalidatePath("/dashboard/invoices");
    return { message: "Deleted Invoice." };
  } catch (error) {
    return { message: "Database Error: Failed to Delete Invoice." };
  }
}
```
![[송장 데이터 삭제 의도적에러발생.png]]

- 이러한 오류를 개발 중에 확인하는 것은 잠재적인 문제를 조기에 발견하는 데 도움이 된다.
	- 하지만 애플리케이션이 갑작스럽게 실패하는 것을 방지하고, 사용자에게 오류를 표시하여 계속 실행되도록 하는 것이 더 **중요**하다! 
	- 이때 Next.js의 `error.tsx` 파일이 유용하게 사용된다.


#### 2. Handling all errors with `error.tsx` (`error.tsx` 파일을 통한 모든 오류 처리)

- `error.tsx` 파일은 특정 라우트 세그먼트에 대한 UI 경계를 정의하는 데 사용된다.
	- Next.js에서 별도로 약속된 파일이다.
	- 이 파일은 예상치 못한 오류를 잡아내고, 사용자에게 대체 UI를 표시할 수 있는 역할을 한다.

- 예시로 `/dashboard/invoices` 디렉터리에 `error.tsx` 파일을 만들고 아래 코드를 붙여넣어보자.
```tsx
"use client";

import { useEffect } from "react";

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // 필요에 따라 오류를 오류 보고 서비스에 로깅
    console.error(error);
  }, [error]);

  return (
    <main className="flex h-full flex-col items-center justify-center">
      <h2 className="text-center">Something went wrong!</h2>
      <button
        className="mt-4 rounded-md bg-blue-500 px-4 py-2 text-sm text-white transition-colors hover:bg-blue-400"
        onClick={() => reset()}
      >
        Try again
      </button>
    </main>
  );
}
```
![[error.tsx.png]]

- 위 `error.tsx` 파일의 코드에서 중요한 점은 아래와 같다.
	1. `"use client"`: `error.tsx` 파일은 클라이언트 컴포넌트여야 한다.
	2. 해당 파일은 항상 두 개의 `props`를 받는다:
	    - `error`: JavaScript의 기본 `Error` 객체.
	    - `reset`: 오류 경계를 리셋하는 함수로, 실행하면 해당 라우트 세그먼트를 다시 렌더링을 시도한다.

- 이제 다시 송장 데이터의 삭제를 진행하려 하면 해당 UI가 표시될 것이다.
![[에러 터질 때 error.tsx 화면.png]]


#### 3. Handling 404 errors with the `notFound` function (`404` 오류를 `notFound` 함수로 처리하기)

- `error.tsx`가 모든 오류를 처리하는 데 유용하긴 하지만, `notFound` 함수는 존재하지 않는 리소스를 요청할 때 사용할 수 있다.

- 예를 들어, 다음 URL을 방문한다고 가정해보자. (해당 URL의 UUID는 DB에 없는 값이다.)
	- `http://localhost:3000/dashboard/invoices/2e94d1ed-d220-449f-9f11-f0bbceed9645/edit`  

- 이 경우에도 물론, `error.tsx`가 동작하여 오류를 처리한다.
	- 하지만 리소스가 없다는 것을 사용자에게 명확히 알려주기 위해 404 오류를 표시할 수 있다.

- 리소스가 존재하지 않는지 확인하기 위해 `fetchInvoiceById` 함수에서 `console.log()`로 확인해보자
```ts

export async function fetchInvoiceById(id: string) {
  noStore();

  try {
    const data = await sql<InvoiceForm>`
      SELECT
        invoices.id,
        invoices.customer_id,
        invoices.amount,
        invoices.status
      FROM invoices
      WHERE invoices.id = ${id};
    `;

    const invoice = data.rows.map((invoice) => ({
      ...invoice,
      amount: invoice.amount / 100,
    }));

    console.log("invoice is ", invoice); // 출력 : invoices is []
    return invoice[0];
  } catch (error) {
    console.error("Database Error:", error);
  }
}
```
![[빈 invoice 출력확인하기.png]]

- 이제, 데이터베이스에 해당 송장데이터가 없다는 것을 확인했으니, 해당 오류를 관리하기 위해 `notFound()` 함수를 사용해볼 수 있다.
	- `/dashboard/invoices/[id]/edit/page.tsx` 파일에서 `notFound()` 함수를 import하고, 송장 데이터가 없을 때 해당 함수를 호출해보자.
```tsx
import Form from "@/app/ui/invoices/edit-form";
import Breadcrumbs from "@/app/ui/invoices/breadcrumbs";
import { fetchCustomers, fetchInvoiceById } from "@/app/lib/data";
import { notFound } from "next/navigation";

export default async function Page({ params }: { params: { id: string } }) {
  const id = params.id;

  // Promise.all을 사용하여 인보이스와 고객 데이터를 동시에 가져옴
  const [invoice, customers] = await Promise.all([
    fetchInvoiceById(id), // 특정 인보이스 데이터를 가져옴
    fetchCustomers(), // 고객 데이터를 가져옴
  ]);

  if (!invoice) notFound();
  
  return (
    <main>
      <Breadcrumbs
        breadcrumbs={[
          { label: "Invoices", href: "/dashboard/invoices" },
          {
            label: "Edit Invoice",
            href: `/dashboard/invoices/${id}/edit`,
            active: true,
          },
        ]}
      />
      <Form invoice={invoice} customers={customers} />
    </main>
  );
}
```

- 위와 같이 코드를 작성하면, 이제 송장 데이터가 없을 경우 `notFound()`함수가 호출된다.
	- 해당 함수가 호출되면, **내부적으로 라우트 세그먼트 범위 내의 `not-found.tsx`파일을 탐색하고, 해당 파일 내용을 렌더링**한다.
	- 이제, 이 내용이 실제로 잘 작동하는지 확인해보기 위해 `edit` 디렉터리 내에 `not-found.tsx` 파일을 생성하고 아래 코드를 추가해보자.

> `/app/dashboard/invoices/[id]/edit/not-found.tsx`
```tsx
import Link from "next/link";
import { FaceFrownIcon } from "@heroicons/react/24/outline";

export default function NotFound() {
  return (
    <main className="flex h-full flex-col items-center justify-center gap-2">
      <FaceFrownIcon className="w-10 text-gray-400" />
      <h2 className="text-xl font-semibold">404 Not Found</h2>
      <p>Could not find the requested invoice.</p>
      <Link
        href="/dashboard/invoices"
        className="mt-4 rounded-md bg-blue-500 px-4 py-2 text-sm text-white transition-colors hover:bg-blue-400"
      >
        Go Back
      </Link>
    </main>
  );
}
```
![[not-found.tsx page.png]]

- 이제, 데이터베이스에 존재하지 않는 UUID의 송장 데이터의 수정 페이지로 진입했을 때 위 이미지와 같은 페이지가 렌더링 된 것을 확인할 수 있을 것이다.
	- 이쯤되어 눈치가 빠른 사람이라면 알아챘겠지만 `notFound()`함수로 호출되어 표시되는 `not-found.tsx`는 `error.tsx`보다 우선순위가 높다.
	- 이는, 특정 오류 상황을 더 구체적으로 처리할 때 `notFound()`함수와 `not-found.tsx` 파일을 를 사용할 수 있다는 뜻이다.


#### 4. 참고 : Route Segment (라우트 세그먼트)

- 위에서 몇 번 **라우트 세그먼트**라고 언급해가면서, 오류페이지를 표시할 수 있다고 말한 부분이 있는데 이게 과연 뭘까?
	- 라우트 세그먼트(route segment)는 **Next.js**에서 URL 경로를 구성하는 각 **경로의 부분**을 의미한다.

- 예를 들어, 다음과 같은 URL이 있다고 가정해 보자.
```bash
http://localhost:3000/dashboard/invoices/edit
```

- 위와 같은 경로의 부분을 뽑아보면 아래와 같이 정리할 수 있겠다. (이게 라우트 세그먼트이다.)
	- `dashboard`
	- `invoices`
	- `edit`

- **Next.js**에서 각각의 세그먼트는 **폴더 구조**와 1:1로 대응한다.
	- 위 URL에 해당하는 폴더 구조는 다음과 같이 정의할 수 있다.
```bash
case 1. app 라우팅
/app/dashboard/invoices/edit.tsx

case 2. page 라우팅
/pages/dashboard/invoices/edit.tsx
```

- Next.js는 각 세그먼트별로 독립적인 **UI 경계**(error boundary)를 설정할 수 있다.
	- 예를 들어, `invoices` 세그먼트에 오류가 발생했을 때, `error.tsx` 파일이 `/dashboard/invoices/` 폴더에 정의되어 있을 경우, 이 세그먼트 내의 오류를 처리할 수 있게 된다.

- 즉, "라우트 세그먼트"는 Next.js에서 특정 경로 또는 URL의 한 부분을 의미하며, 이를 통해 각 라우트 세그먼트마다 개별적으로 오류 처리, 데이터 가져오기, 레이아웃 등을 관리할 수 있도록 하는 기술이라 정리할 수 있겠다.